config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  resource :static do
    get :page_with_filters
    get :page_without_filters
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

  def show
  end

  def page_with_filters
    @show_back = true
    render 'show'
  end

  def page_without_filters

  end

  def update
    cookies[:filter1] = params['filter1'] if params['filter1'].present?
    cookies[:filter2] = params['filter2'] if params['filter2'].present?
    render nothing: :true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turbolinks5PermanentIssue</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/statics/page_without_filters.html.erb
<p>
<strong>
  Now click on back and see that neither the data-turbolinks-permanent dropdown nor the other dropdown maintain value (bad behavior).
</strong>
</p>

app/views/statics/show.html.erb
<p>
  <strong>
    <% if @show_back %>
      Now click on back and see that the data-turbolinks-permanent dropdown maintains it value and the other dropdown does not (good behavior).
    <% else %>
      The dropdowns below are recorded in cookies. <br/>
      Change both dropdowns to a different value than the value loaded by page load. <br/>
      Then perform an application visit using the links below:
      <ul>
        <li><%= link_to 'Second page with the dropdowns', page_with_filters_static_path %> (good behavior)</li>
        <li><%= link_to 'Second page without the dropdowns', page_without_filters_static_path %> (bad behavior)</li>
      </ul>
    <% end %>
  </strong>
</p>


<div id="permanent-div" data-turbolinks-permanent>
  <p>
    <strong>Permanent</strong>
    <br/>
    <%= form_tag static_path, remote: true, method: :patch do %>
      <%= select_tag 'filter1', options_for_select(%w(A B C), cookies[:filter1]), class: 'filter' %>
    <% end %>
  </p>
</div>
<div id="non-permanent-div">
  <p>
    <strong>Non permanent</strong>
    <br/>
    <%= form_tag static_path, remote: true, method: :patch do %>
      <%= select_tag 'filter2', options_for_select(%w(A B C), cookies[:filter2]), class: 'filter' %>
    <% end %>
  </p>
</div>